package com.servicenow.kafka.connect.hermes;

import org.apache.kafka.common.config.AbstractConfig;
import org.apache.kafka.common.config.Config;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigDef.Importance;
import org.apache.kafka.common.config.ConfigDef.Type;
import org.apache.kafka.common.config.ConfigDef.Width;
import org.apache.kafka.common.config.types.Password;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class HermesConnectorConfig extends AbstractConfig {

    // ---- Config key constants ----

    public static final String HERMES_INSTANCE_NAME_CONFIG = "hermes.instance.name";
    public static final String HERMES_TOPIC_CONFIG = "hermes.topic";
    public static final String HERMES_SSL_KEYSTORE_B64_CONFIG = "hermes.ssl.keystore.b64";
    public static final String HERMES_SSL_KEYSTORE_PASSWORD_CONFIG = "hermes.ssl.keystore.password";
    public static final String HERMES_SSL_TRUSTSTORE_B64_CONFIG = "hermes.ssl.truststore.b64";
    public static final String HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG = "hermes.ssl.truststore.password";
    public static final String HERMES_PRODUCER_ACKS_CONFIG = "hermes.producer.acks";
    public static final String HERMES_PRODUCER_RETRIES_CONFIG = "hermes.producer.retries";
    public static final String HERMES_PRODUCER_LINGER_MS_CONFIG = "hermes.producer.linger.ms";
    public static final String HERMES_PRODUCER_BATCH_SIZE_CONFIG = "hermes.producer.batch.size";
    public static final String HERMES_PRODUCER_COMPRESSION_TYPE_CONFIG = "hermes.producer.compression.type";
    public static final String HERMES_SINK_BOOTSTRAP_OVERRIDE_CONFIG = "hermes.sink.bootstrap.override";
    public static final String HERMES_SSL_ENABLED_CONFIG = "hermes.ssl.enabled";
    // Must match InMemorySslEngineFactory.CERT_EXPIRY_WARN_DAYS_CONFIG
    public static final String HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG = "hermes.ssl.cert.expiry.warn.days";

    // ---- Group name constants ----

    private static final String GROUP_CONNECTION = "Connection";
    private static final String GROUP_SECURITY = "Security";
    private static final String GROUP_PRODUCER = "Producer";

    // ---- ConfigDef ----

    public static final ConfigDef CONFIG_DEF = new ConfigDef()
        // Connection group
        .define(
            HERMES_INSTANCE_NAME_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new InstanceNameValidator(),
            Importance.HIGH,
            "ServiceNow instance name (e.g. 'myinstance' from myinstance.service-now.com). " +
            "Used to derive Hermes bootstrap endpoints. Do not include the protocol or domain suffix.",
            GROUP_CONNECTION, 1, Width.LONG, "Instance Name"
        )
        .define(
            HERMES_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Full Hermes topic name to write to, e.g. 'snc.myinstance.sn_streamconnect.my-topic'. " +
            "The connector fails at startup if this topic does not exist in Hermes.",
            GROUP_CONNECTION, 2, Width.LONG, "Hermes Topic"
        )
        // Security group
        .define(
            HERMES_SSL_KEYSTORE_B64_CONFIG,
            Type.PASSWORD,
            "",
            null,
            Importance.HIGH,
            "Base64-encoded PKCS12 keystore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded keystore.p12 file: base64 -i keystore.p12. " +
            "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true (default).",
            GROUP_SECURITY, 1, Width.LONG, "Keystore (Base64)"
        )
        .define(
            HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            "",
            null,
            Importance.HIGH,
            "Password for the PKCS12 keystore. Required when " + HERMES_SSL_ENABLED_CONFIG + "=true (default).",
            GROUP_SECURITY, 2, Width.LONG, "Keystore Password"
        )
        .define(
            HERMES_SSL_TRUSTSTORE_B64_CONFIG,
            Type.PASSWORD,
            "",
            null,
            Importance.HIGH,
            "Base64-encoded PKCS12 truststore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded truststore.p12 file: base64 -i truststore.p12. " +
            "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true (default).",
            GROUP_SECURITY, 3, Width.LONG, "Truststore (Base64)"
        )
        .define(
            HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            "",
            null,
            Importance.HIGH,
            "Password for the PKCS12 truststore. Required when " + HERMES_SSL_ENABLED_CONFIG + "=true (default).",
            GROUP_SECURITY, 4, Width.LONG, "Truststore Password"
        )
        // Producer group
        .define(
            HERMES_PRODUCER_ACKS_CONFIG,
            Type.STRING,
            "all",
            ConfigDef.ValidString.in("0", "1", "all"),
            Importance.MEDIUM,
            "Kafka producer acks setting for writes to Hermes. Default 'all' for durability.",
            GROUP_PRODUCER, 1, Width.SHORT, "Producer Acks"
        )
        .define(
            HERMES_PRODUCER_RETRIES_CONFIG,
            Type.INT,
            Integer.MAX_VALUE,
            ConfigDef.Range.atLeast(0),
            Importance.LOW,
            "Number of retries for the Hermes producer. Default Integer.MAX_VALUE with idempotent producer.",
            GROUP_PRODUCER, 2, Width.SHORT, "Producer Retries"
        )
        .define(
            HERMES_PRODUCER_LINGER_MS_CONFIG,
            Type.INT,
            5,
            ConfigDef.Range.atLeast(0),
            Importance.LOW,
            "Delay in ms before sending a batch. Higher values increase batching.",
            GROUP_PRODUCER, 3, Width.SHORT, "Linger (ms)"
        )
        .define(
            HERMES_PRODUCER_BATCH_SIZE_CONFIG,
            Type.INT,
            16384,
            ConfigDef.Range.atLeast(0),
            Importance.LOW,
            "Max bytes per batch. Matches Kafka producer default.",
            GROUP_PRODUCER, 4, Width.SHORT, "Batch Size"
        )
        .define(
            HERMES_PRODUCER_COMPRESSION_TYPE_CONFIG,
            Type.STRING,
            "none",
            ConfigDef.ValidString.in("none", "lz4", "snappy", "zstd", "gzip"),
            Importance.LOW,
            "Compression algorithm. lz4 recommended for byte payloads.",
            GROUP_PRODUCER, 5, Width.LONG, "Compression Type"
        )
        .define(
            HERMES_SINK_BOOTSTRAP_OVERRIDE_CONFIG,
            Type.STRING,
            "",
            Importance.LOW,
            "Optional bootstrap servers override for the Hermes sink broker. " +
            "When set, replaces the derived '<instance>.service-now.com:4000-4003' address. " +
            "For local development / Docker E2E testing only.",
            GROUP_CONNECTION, 3, Width.LONG, "Sink Bootstrap Override"
        )
        .define(
            HERMES_SSL_ENABLED_CONFIG,
            Type.BOOLEAN,
            true,
            Importance.LOW,
            "Set to false to disable mTLS and use PLAINTEXT. " +
            "For local development / Docker E2E testing ONLY — never disable SSL in production.",
            GROUP_SECURITY, 5, Width.SHORT, "SSL Enabled"
        )
        .define(
            HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG,
            Type.INT,
            30,
            ConfigDef.Range.atLeast(1),
            Importance.LOW,
            "Number of days before mTLS certificate expiration at which a WARN log is emitted. " +
            "Default 30. Set higher for earlier advance warning.",
            GROUP_SECURITY, 6, Width.SHORT, "Cert Expiry Warn Days"
        );

    public HermesConnectorConfig(Map<String, String> props) {
        super(CONFIG_DEF, props);
        if (isSslEnabled()) {
            requireNonEmptySslField(HERMES_SSL_KEYSTORE_B64_CONFIG, getKeystoreB64());
            requireNonEmptySslField(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG, getKeystorePassword());
            requireNonEmptySslField(HERMES_SSL_TRUSTSTORE_B64_CONFIG, getTruststoreB64());
            requireNonEmptySslField(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG, getTruststorePassword());
        }
    }

    private static void requireNonEmptySslField(String key, Password value) {
        if (value == null || value.value().isEmpty()) {
            throw new org.apache.kafka.common.config.ConfigException(
                key, "", "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true");
        }
    }

    public String getInstanceName() {
        return getString(HERMES_INSTANCE_NAME_CONFIG);
    }

    public String getHermesTopic() {
        return getString(HERMES_TOPIC_CONFIG);
    }

    /**
     * Names of every config property treated as a secret. Use this list when
     * uploading the connector to Confluent Cloud:
     *   confluent connect custom-plugin create ... \
     *     --sensitive-properties {@link #SENSITIVE_PROPERTIES_CSV}
     * The {@link Type#PASSWORD} declaration above ensures Kafka Connect masks
     * these in REST and log output; the platform-level sensitive_properties
     * list ensures Confluent Cloud encrypts them at rest.
     */
    public static final List<String> SENSITIVE_PROPERTIES = Collections.unmodifiableList(Arrays.asList(
        HERMES_SSL_KEYSTORE_B64_CONFIG,
        HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
        HERMES_SSL_TRUSTSTORE_B64_CONFIG,
        HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG
    ));

    public static final String SENSITIVE_PROPERTIES_CSV = String.join(",", SENSITIVE_PROPERTIES);

    // Password-typed getters preserve masking when values are passed into the
    // Kafka producer / admin client config map (Password.toString() returns "[hidden]").
    public Password getKeystoreB64() {
        return getPassword(HERMES_SSL_KEYSTORE_B64_CONFIG);
    }

    public Password getKeystorePassword() {
        return getPassword(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG);
    }

    public Password getTruststoreB64() {
        return getPassword(HERMES_SSL_TRUSTSTORE_B64_CONFIG);
    }

    public Password getTruststorePassword() {
        return getPassword(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG);
    }

    public String getProducerAcks() {
        return getString(HERMES_PRODUCER_ACKS_CONFIG);
    }

    public int getProducerRetries() {
        return getInt(HERMES_PRODUCER_RETRIES_CONFIG);
    }

    public int getProducerLingerMs() {
        return getInt(HERMES_PRODUCER_LINGER_MS_CONFIG);
    }

    public int getProducerBatchSize() {
        return getInt(HERMES_PRODUCER_BATCH_SIZE_CONFIG);
    }

    public String getProducerCompressionType() {
        return getString(HERMES_PRODUCER_COMPRESSION_TYPE_CONFIG);
    }

    public String getSinkBootstrapOverride() {
        return getString(HERMES_SINK_BOOTSTRAP_OVERRIDE_CONFIG);
    }

    public boolean isSslEnabled() {
        return getBoolean(HERMES_SSL_ENABLED_CONFIG);
    }

    public int getCertExpiryWarnDays() {
        return getInt(HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG);
    }

    // ---- REST validate() helper ----

    /**
     * Adds cross-field SSL errors to the ConfigValue list returned by Connector.validate() so
     * that missing keystore/truststore values are surfaced by the Connect REST API pre-flight,
     * not only at connector start() time.
     */
    public static void addSslValidationErrors(Map<String, String> props, Config config) {
        boolean sslEnabled = Boolean.parseBoolean(props.getOrDefault(HERMES_SSL_ENABLED_CONFIG, "true"));
        if (!sslEnabled) return;
        for (String key : SENSITIVE_PROPERTIES) {
            String val = props.getOrDefault(key, "");
            if (val.isEmpty()) {
                config.configValues().stream()
                    .filter(cv -> cv.name().equals(key))
                    .findFirst()
                    .ifPresent(cv -> cv.addErrorMessage(
                        "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true"));
            }
        }
    }

    // ---- Validators ----

    static class InstanceNameValidator implements ConfigDef.Validator {
        @Override
        public void ensureValid(String name, Object value) {
            if (value == null || ((String) value).trim().isEmpty()) {
                throw new org.apache.kafka.common.config.ConfigException(
                    name, value, "Instance name must not be blank.");
            }
            String s = (String) value;
            if (s.contains("://") || s.contains("/") || s.contains(":")) {
                throw new org.apache.kafka.common.config.ConfigException(
                    name, value,
                    "Instance name must be the bare instance name only (e.g. 'myinstance'), " +
                    "not a URL. Found unexpected characters: '://'  '/'  or ':'");
            }
        }

        @Override
        public String toString() {
            return "Bare instance name (no protocol, domain, or path components)";
        }
    }
}
