package com.servicenow.kafka.connect.hermes;

import org.apache.kafka.common.config.AbstractConfig;
import org.apache.kafka.common.config.Config;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigDef.Importance;
import org.apache.kafka.common.config.ConfigDef.Type;
import org.apache.kafka.common.config.ConfigException;
import org.apache.kafka.common.config.types.Password;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class HermesSourceConfig extends AbstractConfig {

    // ---- Config key constants ----

    public static final String HERMES_INSTANCE_NAME_CONFIG = "hermes.instance.name";
    public static final String HERMES_SOURCE_TOPIC_CONFIG = "hermes.source.topic";
    public static final String HERMES_CONSUMER_GROUP_ID_CONFIG = "hermes.consumer.group.id";
    public static final String HERMES_DESTINATION_TOPIC_CONFIG = "hermes.destination.topic";
    public static final String HERMES_SSL_KEYSTORE_B64_CONFIG = "hermes.ssl.keystore.b64";
    public static final String HERMES_SSL_KEYSTORE_PASSWORD_CONFIG = "hermes.ssl.keystore.password";
    public static final String HERMES_SSL_TRUSTSTORE_B64_CONFIG = "hermes.ssl.truststore.b64";
    public static final String HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG = "hermes.ssl.truststore.password";
    public static final String HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG = "hermes.consumer.max.poll.records";
    public static final String HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG = "hermes.source.cluster1.bootstrap.override";
    public static final String HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG = "hermes.source.cluster2.bootstrap.override";
    public static final String HERMES_SSL_ENABLED_CONFIG = "hermes.ssl.enabled";
    public static final String HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG = "hermes.ssl.cert.expiry.warn.days";
    public static final String HERMES_CONSUMER_POLL_TIMEOUT_MS_CONFIG = "hermes.consumer.poll.timeout.ms";
    public static final String HERMES_CONSUMER_AUTO_OFFSET_RESET_CONFIG = "hermes.consumer.auto.offset.reset";

    // ---- ConfigDef ----

    public static final ConfigDef CONFIG_DEF = new ConfigDef()
        .define(
            HERMES_INSTANCE_NAME_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new HermesConnectorConfig.InstanceNameValidator(),
            Importance.HIGH,
            "ServiceNow instance name (e.g. 'myinstance' from myinstance.service-now.com). " +
            "Used to derive Hermes bootstrap endpoints for both peer clusters. " +
            "Do not include the protocol or domain suffix."
        )
        .define(
            HERMES_SOURCE_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Full Hermes topic name to read from, e.g. 'snc.myinstance.sn_streamconnect.my-topic'. " +
            "The same topic is consumed from both Hermes peer clusters."
        )
        .define(
            HERMES_CONSUMER_GROUP_ID_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Kafka consumer group.id used by the embedded consumers connecting to Hermes. " +
            "The same group id is used against both peer clusters. " +
            "Hermes ACLs require the group id to be prefixed 'snc.<instanceName>.' — " +
            "the connector applies this prefix automatically if it is not already present."
        )
        .define(
            HERMES_DESTINATION_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Destination topic in Confluent Cloud to which records from Hermes are forwarded."
        )
        .define(
            HERMES_SSL_KEYSTORE_B64_CONFIG,
            Type.PASSWORD,
            "",
            Importance.HIGH,
            "Base64-encoded PKCS12 keystore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded keystore.p12 file: base64 -i keystore.p12. " +
            "Required when hermes.ssl.enabled=true (default)."
        )
        .define(
            HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            "",
            Importance.HIGH,
            "Password for the PKCS12 keystore specified in " + HERMES_SSL_KEYSTORE_B64_CONFIG + ". " +
            "Required when hermes.ssl.enabled=true (default)."
        )
        .define(
            HERMES_SSL_TRUSTSTORE_B64_CONFIG,
            Type.PASSWORD,
            "",
            Importance.HIGH,
            "Base64-encoded PKCS12 truststore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded truststore.p12 file: base64 -i truststore.p12. " +
            "Required when hermes.ssl.enabled=true (default)."
        )
        .define(
            HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            "",
            Importance.HIGH,
            "Password for the PKCS12 truststore specified in " + HERMES_SSL_TRUSTSTORE_B64_CONFIG + ". " +
            "Required when hermes.ssl.enabled=true (default)."
        )
        .define(
            HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG,
            Type.INT,
            500,
            ConfigDef.Range.atLeast(1),
            Importance.LOW,
            "Maximum number of records returned in a single call to poll() by each embedded Hermes consumer."
        )
        .define(
            HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG,
            Type.STRING,
            "",
            Importance.LOW,
            "Optional bootstrap servers override for Hermes source cluster 1. " +
            "When set, replaces the derived '<instance>.service-now.com:4100-4107' bootstrap address. " +
            "For local development / Docker E2E testing only."
        )
        .define(
            HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG,
            Type.STRING,
            "",
            Importance.LOW,
            "Optional bootstrap servers override for Hermes source cluster 2. " +
            "When set, replaces the derived '<instance>.service-now.com:4200-4207' bootstrap address. " +
            "For local development / Docker E2E testing only."
        )
        .define(
            HERMES_SSL_ENABLED_CONFIG,
            Type.BOOLEAN,
            true,
            Importance.LOW,
            "Set to false to disable mTLS and use plaintext. " +
            "For local development / Docker E2E testing ONLY — never disable SSL in production."
        )
        .define(
            HERMES_CONSUMER_POLL_TIMEOUT_MS_CONFIG,
            Type.INT,
            100,
            ConfigDef.Range.atLeast(0),
            Importance.LOW,
            "Maximum milliseconds consumer.poll() will block per cluster. Lower values reduce latency; " +
            "higher values reduce CPU when idle."
        )
        .define(
            HERMES_CONSUMER_AUTO_OFFSET_RESET_CONFIG,
            Type.STRING,
            "earliest",
            ConfigDef.ValidString.in("earliest", "latest", "none"),
            Importance.LOW,
            "Offset reset policy when no stored offset exists for a partition. 'latest' skips historical " +
            "records on first deployment; 'earliest' replays full topic history."
        )
        .define(
            HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG,
            Type.INT,
            30,
            ConfigDef.Range.atLeast(1),
            Importance.LOW,
            "Number of days before mTLS certificate expiration at which a WARN log is emitted. " +
            "Default 30. Set higher for earlier advance warning."
        );

    public HermesSourceConfig(Map<String, String> props) {
        super(CONFIG_DEF, props);
        if (isSslEnabled()) {
            requireNonEmptySslField(HERMES_SSL_KEYSTORE_B64_CONFIG, getKeystoreB64());
            requireNonEmptySslField(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG, getKeystorePassword());
            requireNonEmptySslField(HERMES_SSL_TRUSTSTORE_B64_CONFIG, getTruststoreB64());
            requireNonEmptySslField(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG, getTruststorePassword());
        }
    }

    private static void requireNonEmptySslField(String key, Password value) {
        if (value == null || value.value().isEmpty()) {
            throw new ConfigException(key, "", "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true");
        }
    }

    public String getInstanceName() {
        return getString(HERMES_INSTANCE_NAME_CONFIG);
    }

    public String getSourceTopic() {
        return getString(HERMES_SOURCE_TOPIC_CONFIG);
    }

    public String getGroupId() {
        return getString(HERMES_CONSUMER_GROUP_ID_CONFIG);
    }

    public String getDestinationTopic() {
        return getString(HERMES_DESTINATION_TOPIC_CONFIG);
    }

    /**
     * Names of every config property treated as a secret. Use this list when
     * uploading the connector to Confluent Cloud:
     *   confluent connect custom-plugin create ... \
     *     --sensitive-properties {@link #SENSITIVE_PROPERTIES_CSV}
     * The {@link Type#PASSWORD} declaration above ensures Kafka Connect masks
     * these in REST and log output; the platform-level sensitive_properties
     * list ensures Confluent Cloud encrypts them at rest.
     */
    public static final List<String> SENSITIVE_PROPERTIES = Collections.unmodifiableList(Arrays.asList(
        HERMES_SSL_KEYSTORE_B64_CONFIG,
        HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
        HERMES_SSL_TRUSTSTORE_B64_CONFIG,
        HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG
    ));

    public static final String SENSITIVE_PROPERTIES_CSV = String.join(",", SENSITIVE_PROPERTIES);

    public static void addSslValidationErrors(Map<String, String> props, Config config) {
        boolean sslEnabled = Boolean.parseBoolean(props.getOrDefault(HERMES_SSL_ENABLED_CONFIG, "true"));
        if (!sslEnabled) return;
        for (String key : SENSITIVE_PROPERTIES) {
            String val = props.getOrDefault(key, "");
            if (val.isEmpty()) {
                config.configValues().stream()
                    .filter(cv -> cv.name().equals(key))
                    .findFirst()
                    .ifPresent(cv -> cv.addErrorMessage(
                        "Required when " + HERMES_SSL_ENABLED_CONFIG + "=true"));
            }
        }
    }

    public Password getKeystoreB64() {
        return getPassword(HERMES_SSL_KEYSTORE_B64_CONFIG);
    }

    public Password getKeystorePassword() {
        return getPassword(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG);
    }

    public Password getTruststoreB64() {
        return getPassword(HERMES_SSL_TRUSTSTORE_B64_CONFIG);
    }

    public Password getTruststorePassword() {
        return getPassword(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG);
    }

    public int getMaxPollRecords() {
        return getInt(HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG);
    }

    public String getCluster1BootstrapOverride() {
        return getString(HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG);
    }

    public String getCluster2BootstrapOverride() {
        return getString(HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG);
    }

    public boolean isSslEnabled() {
        return getBoolean(HERMES_SSL_ENABLED_CONFIG);
    }

    public int getCertExpiryWarnDays() {
        return getInt(HERMES_SSL_CERT_EXPIRY_WARN_DAYS_CONFIG);
    }

    public int getPollTimeoutMs() {
        return getInt(HERMES_CONSUMER_POLL_TIMEOUT_MS_CONFIG);
    }

    public String getAutoOffsetReset() {
        return getString(HERMES_CONSUMER_AUTO_OFFSET_RESET_CONFIG);
    }
}
