package com.servicenow.kafka.connect.hermes;

import org.apache.kafka.common.config.AbstractConfig;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigDef.Importance;
import org.apache.kafka.common.config.ConfigDef.Type;

import java.util.Map;

public class HermesConnectorConfig extends AbstractConfig {

    // ---- Config key constants ----

    public static final String HERMES_INSTANCE_NAME_CONFIG = "hermes.instance.name";
    public static final String HERMES_TOPIC_CONFIG = "hermes.topic";
    public static final String HERMES_SSL_KEYSTORE_B64_CONFIG = "hermes.ssl.keystore.b64";
    public static final String HERMES_SSL_KEYSTORE_PASSWORD_CONFIG = "hermes.ssl.keystore.password";
    public static final String HERMES_SSL_TRUSTSTORE_B64_CONFIG = "hermes.ssl.truststore.b64";
    public static final String HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG = "hermes.ssl.truststore.password";
    public static final String HERMES_PRODUCER_ACKS_CONFIG = "hermes.producer.acks";
    public static final String HERMES_PRODUCER_RETRIES_CONFIG = "hermes.producer.retries";

    // ---- ConfigDef ----

    public static final ConfigDef CONFIG_DEF = new ConfigDef()
        .define(
            HERMES_INSTANCE_NAME_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new InstanceNameValidator(),
            Importance.HIGH,
            "ServiceNow instance name (e.g. 'myinstance' from myinstance.service-now.com). " +
            "Used to derive Hermes bootstrap endpoints. Do not include the protocol or domain suffix."
        )
        .define(
            HERMES_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Full Hermes topic name to write to, e.g. 'snc.myinstance.sn_streamconnect.my-topic'. " +
            "The connector fails at startup if this topic does not exist in Hermes."
        )
        .define(
            HERMES_SSL_KEYSTORE_B64_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Base64-encoded PKCS12 keystore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded keystore.p12 file: base64 -i keystore.p12"
        )
        .define(
            HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Password for the PKCS12 keystore specified in " + HERMES_SSL_KEYSTORE_B64_CONFIG
        )
        .define(
            HERMES_SSL_TRUSTSTORE_B64_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Base64-encoded PKCS12 truststore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded truststore.p12 file: base64 -i truststore.p12"
        )
        .define(
            HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Password for the PKCS12 truststore specified in " + HERMES_SSL_TRUSTSTORE_B64_CONFIG
        )
        .define(
            HERMES_PRODUCER_ACKS_CONFIG,
            Type.STRING,
            "all",
            Importance.MEDIUM,
            "Kafka producer acks setting for writes to Hermes. Default 'all' for durability."
        )
        .define(
            HERMES_PRODUCER_RETRIES_CONFIG,
            Type.INT,
            Integer.MAX_VALUE,
            ConfigDef.Range.atLeast(0),
            Importance.LOW,
            "Number of retries for the Hermes producer. Default Integer.MAX_VALUE with idempotent producer."
        );

    public HermesConnectorConfig(Map<String, String> props) {
        super(CONFIG_DEF, props);
    }

    public String getInstanceName() {
        return getString(HERMES_INSTANCE_NAME_CONFIG);
    }

    public String getHermesTopic() {
        return getString(HERMES_TOPIC_CONFIG);
    }

    public String getKeystoreB64() {
        return getPassword(HERMES_SSL_KEYSTORE_B64_CONFIG).value();
    }

    public String getKeystorePassword() {
        return getPassword(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG).value();
    }

    public String getTruststoreB64() {
        return getPassword(HERMES_SSL_TRUSTSTORE_B64_CONFIG).value();
    }

    public String getTruststorePassword() {
        return getPassword(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG).value();
    }

    public String getProducerAcks() {
        return getString(HERMES_PRODUCER_ACKS_CONFIG);
    }

    public int getProducerRetries() {
        return getInt(HERMES_PRODUCER_RETRIES_CONFIG);
    }

    // ---- Validators ----

    static class InstanceNameValidator implements ConfigDef.Validator {
        @Override
        public void ensureValid(String name, Object value) {
            if (value == null || ((String) value).trim().isEmpty()) {
                throw new org.apache.kafka.common.config.ConfigException(
                    name, value, "Instance name must not be blank.");
            }
            String s = (String) value;
            if (s.contains("://") || s.contains("/") || s.contains(":")) {
                throw new org.apache.kafka.common.config.ConfigException(
                    name, value,
                    "Instance name must be the bare instance name only (e.g. 'myinstance'), " +
                    "not a URL. Found unexpected characters: '://'  '/'  or ':'");
            }
        }

        @Override
        public String toString() {
            return "Bare instance name (no protocol, domain, or path components)";
        }
    }
}
