package com.servicenow.kafka.connect.hermes;

import org.apache.kafka.common.config.AbstractConfig;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigDef.Importance;
import org.apache.kafka.common.config.ConfigDef.Type;
import org.apache.kafka.common.config.types.Password;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class HermesSourceConfig extends AbstractConfig {

    // ---- Config key constants ----

    public static final String HERMES_INSTANCE_NAME_CONFIG = "hermes.instance.name";
    public static final String HERMES_SOURCE_TOPIC_CONFIG = "hermes.source.topic";
    public static final String HERMES_CONSUMER_GROUP_ID_CONFIG = "hermes.consumer.group.id";
    public static final String CONFLUENT_TOPIC_CONFIG = "confluent.topic";
    public static final String HERMES_SSL_KEYSTORE_B64_CONFIG = "hermes.ssl.keystore.b64";
    public static final String HERMES_SSL_KEYSTORE_PASSWORD_CONFIG = "hermes.ssl.keystore.password";
    public static final String HERMES_SSL_TRUSTSTORE_B64_CONFIG = "hermes.ssl.truststore.b64";
    public static final String HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG = "hermes.ssl.truststore.password";
    public static final String HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG = "hermes.consumer.max.poll.records";
    public static final String HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG = "hermes.source.cluster1.bootstrap.override";
    public static final String HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG = "hermes.source.cluster2.bootstrap.override";
    public static final String HERMES_SSL_ENABLED_CONFIG = "hermes.ssl.enabled";

    // ---- ConfigDef ----

    public static final ConfigDef CONFIG_DEF = new ConfigDef()
        .define(
            HERMES_INSTANCE_NAME_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new HermesConnectorConfig.InstanceNameValidator(),
            Importance.HIGH,
            "ServiceNow instance name (e.g. 'myinstance' from myinstance.service-now.com). " +
            "Used to derive Hermes bootstrap endpoints for both peer clusters. " +
            "Do not include the protocol or domain suffix."
        )
        .define(
            HERMES_SOURCE_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Full Hermes topic name to read from, e.g. 'snc.myinstance.sn_streamconnect.my-topic'. " +
            "The same topic is consumed from both Hermes peer clusters."
        )
        .define(
            HERMES_CONSUMER_GROUP_ID_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Kafka consumer group.id used by the embedded consumers connecting to Hermes. " +
            "The same group id is used against both peer clusters."
        )
        .define(
            CONFLUENT_TOPIC_CONFIG,
            Type.STRING,
            ConfigDef.NO_DEFAULT_VALUE,
            new ConfigDef.NonEmptyString(),
            Importance.HIGH,
            "Destination topic in Confluent Cloud to which records from Hermes are forwarded."
        )
        .define(
            HERMES_SSL_KEYSTORE_B64_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Base64-encoded PKCS12 keystore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded keystore.p12 file: base64 -i keystore.p12"
        )
        .define(
            HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Password for the PKCS12 keystore specified in " + HERMES_SSL_KEYSTORE_B64_CONFIG
        )
        .define(
            HERMES_SSL_TRUSTSTORE_B64_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Base64-encoded PKCS12 truststore generated by the ServiceNow Instance PKI Certificate Generator. " +
            "Encode the downloaded truststore.p12 file: base64 -i truststore.p12"
        )
        .define(
            HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG,
            Type.PASSWORD,
            ConfigDef.NO_DEFAULT_VALUE,
            Importance.HIGH,
            "Password for the PKCS12 truststore specified in " + HERMES_SSL_TRUSTSTORE_B64_CONFIG
        )
        .define(
            HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG,
            Type.INT,
            500,
            ConfigDef.Range.atLeast(1),
            Importance.LOW,
            "Maximum number of records returned in a single call to poll() by each embedded Hermes consumer."
        )
        .define(
            HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG,
            Type.STRING,
            "",
            Importance.LOW,
            "Optional bootstrap servers override for Hermes source cluster 1. " +
            "When set, replaces the derived '<instance>.service-now.com:4100-4103' address. " +
            "For local development / Docker E2E testing only."
        )
        .define(
            HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG,
            Type.STRING,
            "",
            Importance.LOW,
            "Optional bootstrap servers override for Hermes source cluster 2. " +
            "When set, replaces the derived '<instance>.service-now.com:4200-4203' address. " +
            "For local development / Docker E2E testing only."
        )
        .define(
            HERMES_SSL_ENABLED_CONFIG,
            Type.BOOLEAN,
            true,
            Importance.LOW,
            "Set to false to disable mTLS and use plaintext. " +
            "For local development / Docker E2E testing ONLY — never disable SSL in production."
        );

    public HermesSourceConfig(Map<String, String> props) {
        super(CONFIG_DEF, props);
    }

    public String getInstanceName() {
        return getString(HERMES_INSTANCE_NAME_CONFIG);
    }

    public String getSourceTopic() {
        return getString(HERMES_SOURCE_TOPIC_CONFIG);
    }

    public String getGroupId() {
        return getString(HERMES_CONSUMER_GROUP_ID_CONFIG);
    }

    public String getConfluentTopic() {
        return getString(CONFLUENT_TOPIC_CONFIG);
    }

    /**
     * Names of every config property treated as a secret. Use this list when
     * uploading the connector to Confluent Cloud:
     *   confluent connect custom-plugin create ... \
     *     --sensitive-properties {@link #SENSITIVE_PROPERTIES_CSV}
     * The {@link Type#PASSWORD} declaration above ensures Kafka Connect masks
     * these in REST and log output; the platform-level sensitive_properties
     * list ensures Confluent Cloud encrypts them at rest.
     */
    public static final List<String> SENSITIVE_PROPERTIES = Collections.unmodifiableList(Arrays.asList(
        HERMES_SSL_KEYSTORE_B64_CONFIG,
        HERMES_SSL_KEYSTORE_PASSWORD_CONFIG,
        HERMES_SSL_TRUSTSTORE_B64_CONFIG,
        HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG
    ));

    public static final String SENSITIVE_PROPERTIES_CSV = String.join(",", SENSITIVE_PROPERTIES);

    public Password getKeystoreB64() {
        return getPassword(HERMES_SSL_KEYSTORE_B64_CONFIG);
    }

    public Password getKeystorePassword() {
        return getPassword(HERMES_SSL_KEYSTORE_PASSWORD_CONFIG);
    }

    public Password getTruststoreB64() {
        return getPassword(HERMES_SSL_TRUSTSTORE_B64_CONFIG);
    }

    public Password getTruststorePassword() {
        return getPassword(HERMES_SSL_TRUSTSTORE_PASSWORD_CONFIG);
    }

    public int getMaxPollRecords() {
        return getInt(HERMES_CONSUMER_MAX_POLL_RECORDS_CONFIG);
    }

    public String getCluster1BootstrapOverride() {
        return getString(HERMES_SOURCE_CLUSTER1_BOOTSTRAP_OVERRIDE_CONFIG);
    }

    public String getCluster2BootstrapOverride() {
        return getString(HERMES_SOURCE_CLUSTER2_BOOTSTRAP_OVERRIDE_CONFIG);
    }

    public boolean isSslEnabled() {
        return getBoolean(HERMES_SSL_ENABLED_CONFIG);
    }
}
